### ISSUE TITLE
Transition from using JS to TypeScript

### ISSUE THREAD

**Issue by SheyDenis** [Shabnata/WebProjectASP#18]
Change from using plain JavaScript to use TypeScript.

**Comment by SheyDenis** [comment]
Created branch:
https://github.com/Shabnata/WebProjectASP/tree/TypeScript_Part

Decided this will only affect CheckAvailability() and not replace all JS.
TypeScript is something we don't need in this project but this small part might earn us bonus points.

**Comment by SheyDenis** [comment]
Done.
d7671e48

**Comment by SheyDenis** [comment]
Merged.
b61fb1c25d9ab8f82fc6316a2825eda77da89e80

**Comment by Shabnata** [comment]
1. add / edit brand with same name => ok
2. add / edit category with same name => ok
3. add / edit subcategory with same name => ok

Works
